# Generated by Django 5.1.3 on 2024-11-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_sketch_alter_game_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='game_id',
            new_name='game',
        ),
    ]
