# Generated by Django 5.1.3 on 2024-11-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_game_id_drawing_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sketch',
        ),
    ]
