# Generated by Django 5.1.3 on 2024-11-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_game_sketch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='art',
            field=models.TextField(),
        ),
    ]
