# Generated by Django 5.1.3 on 2024-11-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_drawing_art_alter_game_difficulty_and_more'),
        ('main_app', '0006_alter_game_user'),
    ]

    operations = [
    ]
